package formatter

const (
	happyEmoji         = "😊"
	loveFaceEmoji      = "😍"
	heartsFaceEmoji    = "🥰"
	satisfiedEmoji     = "😌"
	happyCatEmoji      = "😸"
	partyEmoji         = "🥳"
	neutralEmoji       = "😐"
	sadEmoji           = "😞"
	terrorEmoji        = "😱"
	hotEmoji           = "🥵"
	veryHotEmoji       = hotEmoji + terrorEmoji
	coldEmoji          = "🥶"
	veryColdEmoji      = coldEmoji + terrorEmoji
	wetEmoji           = "💦"
	dryEmoji           = "🌵"
	normalHumEmoji     = "🌿"
	pressureEmoji      = "🌀"
	cloudyEmoji        = "☁️"
	clearEmoji         = "🌞"
	bankEmoji          = "🏦"
	stonksEmoji        = "📈"
	airEmoji           = "💨"
	weatherEmoji       = "🏞️"
	emojiRich          = "🤑"
	emojiPoor          = "💸"
	dollarEmoji        = "💵"
	emojiThought       = "🤔"
	maskEmoji          = "😷"
	treeEmoji          = "🌳"
	skullEmoji         = "💀"
	thunderstormEmoji  = "⛈️"
	rainEmoji          = "🌧️"
	snowEmoji          = "❄️"
	foodEmoji          = "🍔"
	homeEmoji          = "🏠"
	educationEmoji     = "🎓"
	communicationEmoji = "📱"
	clothingEmoji      = "👕"
	financeEmoji       = "💰"
	transportEmoji     = "🚗"
	variousEmoji       = "🎉"

	// subgroups
	noSubgroup    = "no_subgroup"
	foodAndDrink  = foodEmoji + "Food & Drink"
	transport     = transportEmoji + "Transport"
	education     = educationEmoji + "Education"
	apartment     = homeEmoji + "Apartment"
	communication = communicationEmoji + "Communication"
	clothing      = clothingEmoji + "Clothing"
	finance       = financeEmoji + "Finance"
	various       = "Various"

	// provider
	provider = "tinygods.dev"
)
